### ISSUE TITLE
INFOGRAFIA DE HILOS .

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/infografia-de-hilos-magaly1311#2]
[MAGALY_NICOLAS_SANCHEZ INFOGRAFIA .pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-magaly1311/files/8394701/MAGALY_NICOLAS_SANCHEZ.INFOGRAFIA.pdf)

**Comment by EvelynLopezz** [comment]
Calificación de la infografía de Magaly Nicolas Sánchez:
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
